version: "3.8"
services:
  app:
    build: .
    container_name: node_ecommerce
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules

  postgres:
    image: postgres:14.1-alpine
    container_name: node_ecommerce_db
    restart: "no"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
